### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by Mihara** [bitcraft/PyTMX#105]
LICENSE file states the project is LGPLv3.

The notice in `pytmx.py` itself, however, as well as all the `*.py` files, says **GPLv3**, which is very much not the same.

**Comment by bitcraft** [comment]
Thanks for noticing that.  I'll get it taken care of.

**Comment by robertpfeiffer** [comment]
As I understand the LGPLv3, this means we can't use PyTMX on the App Store or on consoles where users can't install patched libraries. Maybe on android?, but no switch, no xbone...

Is this intentional?

**Comment by bitcraft** [comment]
IANAL, but LGPL is more permissive than GPL.  The actual wording of "static linking" doesn't apply much to python (all interpreted code) but in sprit, the LGPL is more permissive and reduce the "viral" effects.  You can use LGPL code in an application without "forcing" the rest of it to be GPL.  Again IANAL, but it is more permissive "Lesser" than the GPL.

I don't see how any of that relates to android or app stores.
