### ISSUE TITLE
External image collections tilesets causes KeyError: 'path'

### ISSUE THREAD

**Issue by Powalski** [bitcraft/PyTMX#108]
Loading a TiledMap based on an external tileset which doesn't consist of a single image causes an error :
```
Traceback (most recent call last):
  File "D:/[...]/test_external_tileset.py", line 3, in <module>
    tmx = pytmx.TiledMap('test_external_tileset.tmx')
  File "C:\Users\stpwsk\Anaconda3\lib\site-packages\pytmx\pytmx.py", line 360, in __init__
    self.parse_xml(ElementTree.parse(self.filename).getroot())
  File "C:\Users\stpwsk\Anaconda3\lib\site-packages\pytmx\pytmx.py", line 400, in parse_xml
    self.add_tileset(TiledTileset(self, subnode))
  File "C:\Users\stpwsk\Anaconda3\lib\site-packages\pytmx\pytmx.py", line 845, in __init__
    self.parse_xml(node)
  File "C:\Users\stpwsk\Anaconda3\lib\site-packages\pytmx\pytmx.py", line 894, in parse_xml
    p["path"] = os.path.join(os.path.dirname(source), p["path"])
KeyError: 'path'
```

Steps to reproduce : 

1. Create a new tileset (select Type : Collection of Images, uncheck 'Embed in map')
2. Add at least one tile in this tileset
3. Save and close it
4. Create a new map (default settings)
5. Add the previously created tileset to the map (shortcut : Alt-m-a)
6. Save and close the map
7. Load it in python `tmx = pytmx.TiledMap('test_external_tileset.tmx')`

I think this bug is caused by #103 at [line 892](https://github.com/bitcraft/PyTMX/blob/master/pytmx/pytmx.py#L892). The check should be performed at [line 902](https://github.com/bitcraft/PyTMX/blob/master/pytmx/pytmx.py#L902), as it concerns the image. Furthermore, according to the [Tiled docs](https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#tmx-image) there is no field named 'path', thus the KeyError - I think it should be 'source'.

**Comment by bitcraft** [comment]
pytmx must be too out of date to support this.  Unfortunately i don't have much time to test.  Do you mind sharing your images and maps?  It will help speed up the process.  This needs new code...not a simple bug fix.

**Comment by Powalski** [comment]
Here is a minimal example of a map that isn't loaded correctly :
In main folder :
- [external_tileset_as_collection_of_images.txt](https://github.com/bitcraft/PyTMX/files/2703450/external_tileset_as_collection_of_images.txt)
- 'tilesets' folder

In 'tilesets' folder :
- [tileset_as_collection_of_images.txt](https://github.com/bitcraft/PyTMX/files/2703456/tileset_as_collection_of_images.txt)

Github wasn't happy with .tmx / .tsx files so I changed the extensions, the first one (external_tileset_as_collection_of_images) is a .tmx file and the second (tileset_as_collection_of_images) a .tsx

What do you mean by 'new code' ? Wouldn't changing some of the lines 886 - 905 be enough to fix this? I tried this and it seems to work, but maybe I'm missing something?
```
for child in node.getiterator('tile'):
    tiled_gid = int(child.get("id"))

    p = {k: types[k](v) for k, v in child.items()}
    p.update(parse_properties(child))

    # # remove this
    # if source:
    #     p["path"] = os.path.join(os.path.dirname(source), p["path"])

    # handle tiles that have their own image
    image = child.find('image')
    if image is None:
        p['width'] = self.tilewidth
        p['height'] = self.tileheight
    else:
        tile_source = image.get('source')  # add those lines
        if source:
            tile_source = os.path.join(os.path.dirname(source), tile_source)
        p['source'] = tile_source
        p['trans'] = image.get('trans', None)
        p['width'] = image.get('width')
        p['height'] = image.get('height')
```

**Comment by bitcraft** [comment]
"new code" means handling new images.  right now pytmx assumes there is a 1:1 relationship between tilesets and the image.  so, there will have to be additional code to handle that.  thanks for uploading the files (txt extension is fine).  not sure when i can look at it (with christmas right around the corner)

**Comment by Powalski** [comment]
Oh okay I see! I'll take a deeper look on the entire library to get a better understanding of this bug.
No problem there's no hurry ;-)

**Comment by Pygasm** [comment]
I have this exact same issue. Any updates on this?

**Comment by bitcraft** [comment]
I am on vacation until 1/8 and will likely not be able to address until after that.  Patches are welcome, of course.

**Comment by bitcraft** [comment]
Hi!  Long time no chat.  I've uploaded a possible fix for your issue?  Do you mind trying it out?  Update to version `2.16.7`.

**Comment by robertpfeiffer** [comment]
That commit 38519b94ab9a2db7cacb8e18de4d83750ec6fac2 finally made my commit 078dee6ae2a683f540a2154ce9ff214d2c260640 obsolete and solved *one* of the problems for me

**Comment by Powalski** [comment]
Hi!
As mentionned by @robertpfeiffer, the latest version does fix the KeyError being raised, but not the underlying problem which led to commit #103 : in the case where an external tileset.tsx file is not located in the same directory as the tiledmap.tmx file, the source of the image.png files is wrong and causes an error.
Unfortunately, I still don't get the whole gid mapping process, but I don't think it is relevant for this bug, so I opened a pull request (#112).
