### ISSUE TITLE
Alpha tilesets with "trans" specified causes images to be loaded incorrectly

### ISSUE THREAD

**Issue by clauded07** [bitcraft/pytmx#111]
Hi,
I have problem with some tiles (tileset) are not transparent with pytmx but ok with tiled map editor ??
I try to change on tmx file trans="000000" to ffffff, but same problem. the tilesets png have really transparent background. i take tileset from lpc.opengameart.org
some body have the same problem?
screen copy are on [https://discourse.mapeditor.org/t/problem-render-alpha-tiled-pytmx/3705](https://discourse.mapeditor.org/t/problem-render-alpha-tiled-pytmx/3705)
Thanks

**Comment by bitcraft** [comment]
Your version of pytmx is really old.  Try updating.  Current version is 3.21.6.

Could you link the code you are using?

**Comment by bitcraft** [comment]
Thanks for uploading these files.  If I remove "trans" from the tmx files. they work fine.  Did you add that yourself?  Trans is for images with a special color for transparency ("colorkey").

![image](https://user-images.githubusercontent.com/556711/52011412-7ac97800-249d-11e9-8d3d-d80216e72ea6.png)

**Comment by bitcraft** [comment]
I also found a regression where images were not loading, so please update to 2.16.7 and try again

**Comment by clauded07** [comment]
Ho yes! when i remove "trans" of tmx file, it is good !
"Trans" is add automaticly by tiled map editor. I ll remove all "trans" now.
Thanks you very much!

2.16.7 without remove "trans" as similary problem.

**Comment by bitcraft** [comment]
Interesting.  Trans doesn't make sense.  I'll try to figure out why it gets added and account for it.  Leaving this open and adjusting the bug title.
