### ISSUE TITLE
converting 2014 pytmx to now

### ISSUE THREAD

**Issue by metulburr** [bitcraft/PyTMX#114]
Ive written a basic example of pytmx back in 2014. 

https://github.com/metulburr/rpg_test

The problem was back then pytmx was only python2.x. To update, i downloaded the latest pytmx, and plopped it in. But what i have found is a ton of name changes since then making the process a nightmare to convert over. Simple things like TiledLayer is now TiledTileLayer, or going from camelcase to underscore such as GetTileImageByGID is now get_tile_image_by_gid
My current issue is i cannot find the replacement of GetObects
```
    def make_blockers(self, blocker_name):
        blockers = pg.sprite.Group()
        for obj in self.renderer.tmx.GetObjects():
            properties = obj.__dict__
            if properties['name'] == blocker_name:
                x = properties['x']
                y = properties['y']
                width = properties['width']
                height = properties['height']
                blocker = pg.sprite.Sprite()
                blocker.state = None
                blocker.rect = pg.Rect(x, y, width, height)
                blockers.add(blocker)
```
Could it be possible to make a conversion instruction of changes or help change my template?

**Comment by bitcraft** [comment]
The early releases were really rough around the edges.  Sorry there is no documentation on those changes since they happened around 2015 i think.
