### ISSUE TITLE
boolean Tile properties casted incorrectly

### ISSUE THREAD

**Issue by jonsole** [bitcraft/PyTMX#115]
If a tile has a boolean property, for example:

    <tile id="0">
      <properties>
        <property name="IsWall" type="bool" value="false"/>
      </properties>
    </tile>

when that property is accessed using get_tile_properties, the value of the property (in this case IsWall) is always True.

The issue is in parse_properties, it tries to cast the string "false" to a boolean by effectively doing bool("false").  This will return True not False as expected.

**Comment by jonsole** [comment]
Changing the bool entry in prop_type to:

    'bool': convert_to_bool,

and then changing the code in parse_properties from:

               if "type" in subnode.keys():
                    module = importlib.import_module('builtins')
                    cls = getattr(module, subnode.get("type"))

to:

                if "type" in subnode.keys():
                    cls = prop_type[subnode.get("type")]

fixes the issue for me.

**Comment by macskay** [comment]
I simply added a ternary operator to check if the value is any permutation of "false" in regards to lower- and uppercasing. Furthermore the user can now even put in 0 or 1 for values in the tmx file.

**Comment by macskay** [comment]
Fix was to check if the value is any form of "false" or "0" and return False when it is, otherwise the value itself.
cls("" if value.lower() == "false" or (value.isdigit() and int(value) == 0) else value)

**Comment by bitcraft** [comment]
Thanks for the report.  I will integrate your changes.

**Comment by bitcraft** [comment]
@jonsole should be fixed in latest commit.
