### ISSUE TITLE
pygame2 renderer support

### ISSUE THREAD

**Issue by mcpalmer1980** [bitcraft/PyTMX#117]
I recently created a loader for the experimental pygame2 renderer, which of course was easy. I'm also planning to port pyscroll to the pygame2 texture renderer once the final api is documented.

My long term goal is to add c-optimized algos for raycasting, a* pathfinding, lighting, particle collisions, and whatever other features deemed necessary for the modern pygame2 framework to truly shine.

Wondering if anyone else is interested in this, especially bitcraft.

**Comment by bitcraft** [comment]
Hey @mcpalmer1980 yeah I would love to get that integrated with pytmx as an image loader.  Lets discuss the details here before opening a pr.  Try to follow the same pattern as the existing ones.  The pygame loader is a good start.  The pyglet loader is also good.

**Comment by mcpalmer1980** [comment]
It was so long ago that I wrote that loader I don't remember the details. I think I used partial to pass in a render context. It was fairly easy to implement but i didn't continue with it because pyscroll's design doesn't seem ideal for use with pygame2 rendering/sprite batching.

As I recall pyscroll blits perhaps a 4x4 grids of cells into buffer surfaces as the tilemap scrolls in a new direction. This is unnecessary when using pygame2's sdl2 extensions, because rendering textures is practically free. It's the looping and processing in python that is the limitation. Ideally, a tight C loop that draws the necessary cells based on a global transform matrix(location, rotation, and scale) would be used.

Pygame member blubberquark claims to be planning or working on something like this as an add-on module for pygame2. I think using pytmx for loading the tiles into his renderer would grant a good head start.

I am eager to have nearly endless tilemaps that can rotate and scale in pygame, and perhaps a particle engine that interacts with the tile data too. But the bulk of this would be best in c I think. Perhaps you should coolaberate with blubberquark, who's far more advanced than me. He hangs out on the pygame [discord server](https://discord.gg/ThkZD2) quite frequently.

**Comment by bitcraft** [comment]
Thanks for the update.  I agree that pyscroll as is would not be a good fit
for a graphics library which can manage its own textures in memory
quickly.  Pyscroll creates a single buffer, slightly larger that the window
and only draws tiles around the edges of the buffer.

Pyscroll can handle endless scrolling as is.  I don’t think C is needed
because I get almost 800 FPS 1080p on my old computer and that is pure
python and pygame.  It’s nice to have the C code, but for a desktop
computer I don’t believe it’s needed.  That said, I am biased because I
don’t love C.

blubberquark has made some contributions (maybe just to pytmx)...  I’ll
maybe work on pyscroll more when pygame 2 is no longer beta.  It’s nearly
feature complete right now.

On Thu, Apr 16, 2020 at 2:37 PM mcpalmer1980 <notifications@github.com>
wrote:

> It was so long ago that I wrote that loader I don't remember the details.
> I think I used partial to pass in a render context. It was fairly easy to
> implement but i didn't continue with it because pyscroll's design doesn't
> seem ideal for use with pygame2 rendering/sprite batching.
>
As I recall pyscroll blits perhaps a 4x4 grids of cells into buffer

**Comment by mcpalmer1980** [comment]
I assume you mean that you get 800fps with pyscroll and pygame 1.9x, or perhaps pygame2 but without texture rendering. I agree that pyscroll is great as it is. It only has to deal with one row and/or column at at time.

The situation where I see tight c loops useful is for pygame2 when rendering or updating every cell on screen(say 32px cells at 1080p = 60 rows of 34 columns, or 2040 cells).

**Comment by bitcraft** [comment]
If moving to pygame2 requires C code to be faster with hardware textures
than software rendering with python code there is a problem.

**Comment by mcpalmer1980** [comment]
It doesn't require C code to be faster than software blitting if all you want is the same behavior pyscroll already offers. There's several ways to reproduce pyscroll with hardware rendering that will use far less cpu time for the same results.

But what if I want more? Such as animated tiles on almost all cells, while zooming and rotating? Or 5 tile layers with 3 of them parallax? A very large map with 100s of grass tiles that animate in the wind would require a lot of looping to change their image every frame.

I would feel better knowing that the tilemap renderer is as efficient as possible, leaving resources for me to add tons of other things else in pure python without worrying about pegging my CPU (or the one in a smartphone or retro console).

**Comment by bitcraft** [comment]
Ok. I feel that this discussion is now out of scope. If there is no code to commit for pygame2 the I think we’ve said enough and I’ll close this issue.  When pygame2 is out of beta this can be discussed again.
