### ISSUE TITLE
Property type bool load correctly

### ISSUE THREAD

**Issue by Alec-15** [bitcraft/pytmx#125]
When adding a Property of type Bool to an object it will always be loaded with the value of True.

The issue can be seen here:

> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytmx/pytmx.py(212)parse_properties()
-> d[subnode.get('name')] = cls(subnode.get('value')) if cls is not None else subnode.get('value')
(Pdb) p cls
<class 'bool'>
(Pdb) subnode.get('name')
'open'
(Pdb) subnode.get('value')
'false'
(Pdb) cls(subnode.get('value'))
True
(Pdb) cls('False')
True
(Pdb) cls(False)
False
(Pdb) cls('')
False
(Pdb) cls()
False

**Comment by paulbaumgarten** [comment]
Confirm. I'm having the same issue.

Here is an example property dictionary:

```
{'id': 178, 'climbable': 1, 'ground': True, 'health': 0, 'points': 0, 'provides': '', 'requires': 'red key', 'solid': True, 'source': 'tiles/lock_red.png', 'trans': None, 'width': '70', 'height': '70', 'frames': []}
```

And the corresponding xml from the tileset.

```
<tile id="178">
  <properties>
   <property name="climbable" type="int" value="1"/>
   <property name="ground" type="bool" value="false"/>
   <property name="health" type="int" value="0"/>
   <property name="points" type="int" value="0"/>
   <property name="provides" value=""/>
   <property name="requires" value="red key"/>
   <property name="solid" type="bool" value="false"/>
  </properties>
  <image width="70" height="70" source="tiles/lock_red.png"/>
 </tile>
```

**Comment by bitcraft** [comment]
do you have the latest version installed?  it might not be on pip right now

**Comment by paulbaumgarten** [comment]
You're right. I've got 3.21.7 which is what was installed via pip. It's not practical to upgrade manually as I'm using pytmx with middle schoolers over zoom based remote classes... which is complicated enough as it is :-/

I can live with it for now. I had the class use Tiled Map Editor to convert all the booleans to ints and I got to each them about using 0s and 1s as an alternative way of denoting truthiness ;-)

Thanks

**Comment by bitcraft** [comment]
I'll get the pip version upgraded for you and the class shortly.

**Comment by bitcraft** [comment]
@paulbaumgarten i've uploaded the latest version to pypi.

**Comment by paulbaumgarten** [comment]
> @paulbaumgarten i've uploaded the latest version to pypi.

Thank you kindly 👍
