### ISSUE TITLE
properties don't support 'object' type

### ISSUE THREAD

**Issue by ElePhantom864** [bitcraft/pytmx#130]
```
    cls = prop_type[subnode.get("type")]
KeyError: 'object'
```

**Comment by bitcraft** [comment]
can you paste your tmx file please?

**Comment by kanekv** [comment]
@bitcraft we took a look and here: https://github.com/bitcraft/pytmx/blob/master/pytmx/pytmx.py#L171-L178 object type is missing. We can provide a PR that adds missing functionality if you are ok with it.

Here is relevant part from tmx file:
```
  <object id="61" name="cobra" x="488" y="776" width="16" height="16">
   <properties>
    <property name="route1" type="object" value="62"/>
   </properties>
  </object>
  <object id="62" name="cobra1" x="496" y="880">
   <point/>
  </object>
```

**Comment by bitcraft** [comment]
yep. i see what you are saying.  i've just added it.  thanks for letting me know.

**Comment by ElePhantom864** [comment]
@bitcraft I have slightly more extensive patch coming, please review

**Comment by bitcraft** [comment]
thank you, i've merged your patch
