### ISSUE TITLE
Bypassing Smart Convert

### ISSUE THREAD

**Issue by LGgameLAB** [bitcraft/pytmx#135]
I'm trying to generate a Tiled map preview on a website with django. I was going to use pygame to generate the image however due to the smart convert built into the pytmx.load_pygame, it requires me to initialize the pygame display which would not be ideal for a server program. Is there a way to easily generate an image with pytmx or bypass the converting process when you load it into pygame? Thanks

**Comment by bitcraft** [comment]
You can use a dummy video driver or run the script with Xvfb.  Another
option would be using a lib that doesn’t require a display such as PIL, but
you would need to rewrite the drawing and loading code.

I’d try the dummy driver first then Xvfb.

**Comment by bitcraft** [comment]
Just thinking about smart convert specifically, you could try to make a new image loader and call `convert_alpha` each tile (just copy/paste the existing one and modify it.  that might work.  Use the new loader like this:
```
tmxmap = pytmx.TiledMap(filename, image_loader=my_image_loader)
```

**Comment by LGgameLAB** [comment]
Thank you bitcraft. The best solution for me would be to develop my map preview image with PIL which I am totally okay with. I am not sure how I would go about using PIL with pytmx. Can I iterate through the tiles the same as when I do with pygame. Is there a tutorial on this. Thanks

**Comment by bitcraft** [comment]
There are no tutorials, but you would follow roughly the same steps as the pygame image loader.  You would open the file and a PIL.Image, then extract tiles using Image.crop.  The final map would be drawn using Image.Composite to draw tiles.  For tile operations there are scale, rotate, etc.  All of that is done in the pygame loader and wouldn't be much different for PIL.

**Comment by bitcraft** [comment]
https://github.com/bitcraft/pytmx/blob/master/pytmx/util_pygame.py#L87

**Comment by LGgameLAB** [comment]
Thanks bitcraft
I tried making my own version but I do not know how to use PIL very well or how I could utilize Image.composite. The code below is what I attempted but the bottom layers weren't showing up so I put that break there and it turns out the bottom layer seemingly wasn't doing anything to the original image. Only the top layer showed. Could you tell me where I went wrong or maybe how to use Image.composite to make this work. Thanks for your time.
 
`import pytmx
from PIL import Image
import os

PATH = os.path.dirname(os.path.abspath(__file__))

mapDir = 'assets/Tiled/level1/level1.tmx'

tmxdata = pytmx.TiledMap(os.path.join(PATH, mapDir))
width = tmxdata.width * tmxdata.tilewidth
height = tmxdata.height * tmxdata.tileheight
levelSize = (width, height)
img = Image.new("RGB", levelSize, (0, 0, 0))
tileSize = 32

tile = tmxdata.get_tile_image_by_gid
for layer in tmxdata.visible_layers:
    if isinstance(layer, pytmx.TiledTileLayer):
        for x, y, gid, in layer:
            tileData = tile(gid)
            if not tileData is None:
                tileImgDir = tileData[0]
                ts = Image.open(tileImgDir,)
                tileImg = ts.crop(tileData[1])
                img.paste(tileImg, (x * tmxdata.tilewidth, y * tmxdata.tileheight))
    break

img.save("map.png")`

**Comment by bitcraft** [comment]
In one of my messages I said you should make an image loader.  If you make an image loader then all the tile sets and images will be loaded.  You must make an image loader.  Copy and paste the pygame image loader then adapt it for PIL.  Then all the tiles will be loaded abs you won’t be missing layers.

**Comment by LGgameLAB** [comment]
Sorry I completely misunderstood you. I am working on a pil_image_loader that should hopefully make it work.

**Comment by LGgameLAB** [comment]
Alright I got it to work! If you want the  the PIL image loader I made I can give it to you. Thanks for your help and creating this cool python library.

**Comment by bitcraft** [comment]
That’s great you’ve figured it out.  If you’ve got it working, I’m sure others would find it useful.  A pr would be best, but you can also copy paste it here and I can add it.

**Comment by LGgameLAB** [comment]
Okay. It is very simple but I believe it will spare other's time if they want to develop something that were to include the basic image/PIL output.  

`def pil_image_loader(filename, colorkey, **kwargs):`
    """ pytmx/LGgameLAB image loader for PIL TMX Maps
    :param filename:
    :param colorkey:
    :param kwargs:
    :return:
    """
    if colorkey:
        colorkey = pygame.Color('#{0}'.format(colorkey))

    pixelalpha = kwargs.get('pixelalpha', True)
    image = Image.open(filename)

    def load_image(rect=None, flags=None):
        if rect:
            try:
                rectP = pygame.Rect(rect)
                left = rectP.x
                top = rectP.y
                right = rectP.x + rectP.width
                bottom = rectP.y + rectP.height
                tile = image.crop((left, top, right, bottom))
                
            except SystemError: ## System error for PIL instead of value
                logger.error('Tile bounds outside bounds of tileset image')
                raise
        else:
            tile = image.copy()

        if flags:
            print("Flag not operable on PIL Image")

        return tile

    return load_image`
