### ISSUE TITLE
PYTMX not returning anything in Custom Properties dictionary for Objects

### ISSUE THREAD

**Issue by MaximumCDawg** [bitcraft/pytmx#139]
Hello! Thank you so much for PYTMX. Within a week of learning Python, it has allowed me to be well on my way to making my game engine. I have had no trouble learning the ropes so far, but now that I'm trying to use the Object Layers, instead of just Tile Layers, I have encountered a problem I can't figure out.

Basically, I can't read Custom Properties information from Objects. I can read them from Tiles on the tile layer just fine. The following code works great, finding my custom property "solid" on tiles:

        if (self.vector[0] < 0): #moving left
            tile_to_check1 = get_tile_properties(tmxdata, self.rect.x+self.vector[0], self.rect.y+(TILESIZE/4))
            tile_to_check2 = get_tile_properties(tmxdata, self.rect.x+self.vector[0], self.rect.y+(TILESIZE/2))
            tile_to_check3 = get_tile_properties(tmxdata, self.rect.x+self.vector[0], self.rect.y+TILESIZE-1)
            if (tile_to_check1['solid'] == True) or (tile_to_check2['solid'] == True) or (tile_to_check3['solid'] == True):
                self.vector[0]=0

And, I can read Names from Objects just fine. The following works great:

    def player_enters_map(self, tmxdata):

        for layer in tmxdata.visible_layers:
            if(isinstance(layer,pytmx.TiledTileLayer)):
                for tile_object in tmxdata.objects:
                    if (tile_object.name == "entrance"):
                        self.player.setpos(tile_object.x,tile_object.y)

BUT, when I try to actually read Custom Properties from an object, I get an empty dictionary and a KeyAccess error:
        
    def check_for_map_exit(self, tmxdata):
   
        for tile_object in tmxdata.objects:
            if(tile_object.name == 'exit'):
                player_rect = Rect(self.player.rect)
                exit_object_rect = Rect(tile_object.x,tile_object.y,tile_object.width,tile_object.height)
        
                # If the player is intersecting the exit object, need to load a new screen.
                if(pygame.Rect.colliderect(player_rect,exit_object_rect)):
                    print(tile_object.properties)
                    return tile_object.properties['dest']
                
        return "no exit"

That last code prints out an empty dictionary : {} and then it throws a KeyError and tells me there is no "dest" in the dictionary. But, I assure you, I have indeed created a Custom Property named "dest" in that object and saved it. Any ideas what I am missing about how to access it?

**Comment by bitcraft** [comment]
> for tile_object in tmxdata.objects:

This may be your problem.  `tmxdata.objects` will iterate all the object in the map, including walls, spawn points, and tile_objects, etc.  You will need to verify that the object that you are checking is a tile object.  It should have a GID, so you can check that.  If that doesn't help, please share the TMX file you are using (just the file, i don't need the other data) and I can inspect it.

**Comment by MaximumCDawg** [comment]
I have attached the tmx file in question. 

[Notlevel1.zip](https://github.com/bitcraft/pytmx/files/6141933/Notlevel1.zip)

I'm not following you on the GID. The object I find does have the correct name, "exit," and I don't use many other objects on this map. There are enemy spawn points, a player entrance, and a player exit, and that's it.

**Comment by bitcraft** [comment]
thanks for sharing that.

> I'm not following you on the GID

you mentioned "tile object".  in Tiled, there are specific types of objects which look like a tile, but are an object.  they are called "tile objects" in the code, so i thought you were using "tile objects", but it appears you are just using plain objects.  so there was some confusion, but i understand now.

here is a bit from the XML
```xml
<objectgroup id="6" name="Object Layer 1">
<object id="13" name="player_spawn" x="190.5" y="360.333"/>
<object id="14" name="enemy_spawn" x="675" y="305.833"/>
<object id="16" name="enemy_spawn" x="471.333" y="366.5"/>
<object id="17" name="enemy_spawn" x="942.667" y="307.833"/>
<object id="18" name="enemy_spawn" x="905.833" y="393.667"/>
<object id="19" name="enemy_spawn" x="1305.33" y="399.333"/>
<object id="20" name="enemy_spawn" x="1508.67" y="271.334"/>
<object id="21" name="enemy_spawn" x="1814.66" y="398.666"/>
<object id="22" name="enemy_spawn" x="2253.33" y="382"/>
<object id="23" name="enemy_spawn" x="2080" y="322"/>
<object id="24" name="enemy_spawn" x="2416.67" y="381.333"/>
<object id="25" name="enemy_spawn" x="2159.33" y="98"/>
<object id="26" name="enemy_spawn" x="2528.67" y="161.333"/>
<object id="27" name="enemy_spawn" x="2646.67" y="242.667"/>
<object id="28" name="exit" x="-35.3333" y="0.666667" width="49.3333" height="490.667"/>
<object id="29" name="entrance" x="46" y="366.667"/>
</objectgroup>
```
notice that there are not properties stored in the file, so i think that maybe you are using the wrong map, or the maps are not saved correctly.  if there were properties for "dest", then they would be in this file, but i'm not seeing it here.

**Comment by MaximumCDawg** [comment]
Wow. You're 110% right. I was unknowingly editing an older version of the map in a different directory. As soon as I worked on the correct map, my code worked immediately.

Thanks! Hopefully the code snippets help someone else with similar questions.

**Comment by bitcraft** [comment]
thanks for including all the code and a background to the problem in the initial post.  it was helpful to solve it quickly.
