### ISSUE TITLE
how to make animations in pygame work?

### ISSUE THREAD

**Issue by Pykitty-Pykatty** [bitcraft/pytmx#140]
So I was making a game with some animated tiles and when I loaded a map the animated tiles didn't animate. Is there a setting for this?

**Comment by bitcraft** [comment]
pytmx is a map loader and doesn't really do much for the rendering of tiles and though there are some included examples on how the basics work, pytmx is not a renderer.  animations are part of a tile's properties.  here is a code snippet from another library, pyscroll, which supports tile animations:
```python
    def get_animations(self):
        for gid, d in self.tmx.tile_properties.items():
            try:
                frames = d['frames']
            except KeyError:
                continue
            if frames:
                yield gid, frames
```
you need to get the animations for every tile, then schedule them to change, depending on each frame duration.  you can use pyscroll for a reference, or use it in place of whatever renderer you are using now.  https://github.com/bitcraft/pyscroll/blob/master/pyscroll/data.py#L280
