### ISSUE TITLE
Writing and Redrawing Tiled Maps

### ISSUE THREAD

**Issue by MaximumCDawg** [bitcraft/pytmx#146]
I am dimly aware of the idea that Pytmx is a Tiled Map "loader," not necessarily a Tiled Map "writer," but it seems like the set_properties() function should allow me to make changes to a loaded Tiled Map on the fly. In particular, I am trying to use the Object layer of Tiled to mark tiles on the Tilemap that are "destructible" blocks. The behavior I want is that, when the player_projectile object encounters a breakable Object, it plays a little animation and rewrites the tile at that location on the Tilemap layer to be a blank tile of id=0. My code appears to be properly changing the id and other properties, like solidity, but not the image being drawn.

This is the method I am using to try and "clear" a tile:

def write_tile_properties(tmxdata,coords_to_change):
    
    #coords_to_change = A tuple with (x,y)
    #new_image = The new GID you want to write.
    #new_properties = A dictionary with the new properties you want to write.\
    
    clear_surface = pygame.Surface((TILESIZE,TILESIZE),pygame.SRCALPHA)
    clear_surface.fill
    clear_surface.set_alpha(255)
    
    # Create a dictionary that lists off the properties of a blank tile
    new_properties = {
        "id": 0,
        "image": clear_surface,
        "solid": False,
        "platform": False,
        "push_rock": False,
        "sand": False,
        "spike_large": False,
        "spike_small": False
    }
    
    world_x = coords_to_change[0];
    world_y = coords_to_change[1];
    tile_x = world_x // TILESIZE
    tile_y = world_y // TILESIZE
    
    try:
        tile_gid = tmxdata.get_tile_gid(tile_x,tile_y,BLOCK_LAYER)
    except Exception:
        print("exception thrown; cant find tile data")
    
    # Load the blank tile into position
    tmxdata.set_tile_properties(tile_gid,new_properties)

(The large number of properties are just those I am using in my map for interaction with various parts of my game.)

After doing this, I instruct my main function that the Tiled Map has been altered (in memory anyway) and that it needs to redraw the map. I don't redraw every frame otherwise. Here's my draw function:

def blit_all_tiles(window, tmxdata, screen_offset):

    window.fill(0)
    for layer in tmxdata.visible_layers:
        # Game will crash if we try to blit the object layer, so make sure we're
        # not doing that. Make sure it's a Tile Layer instead.
        if isinstance(layer, pytmx.TiledTileLayer):
            for tile in layer.tiles():
                #tiles[0] = z grid location
                #tiles[1] = y grid location
                #tiles[2] = image data for blitting
                x_pixel = tile[0] * TILESIZE + screen_offset[0]
                y_pixel = tile[1] * TILESIZE + screen_offset[1]
                window.blit( tile[2], (x_pixel, y_pixel))

As I said, this sort of works. The properties of the tile do indeed change, and if I add a print() trace I can see that they did. The id changes to 0 just like it should. But, the image for that tile stubbornly refuses to change. The end result is that the player can walk through the broken tile, but it doesn't disappear graphically like it should.

Is there something about writing to properties that I am missing?

**Comment by bitcraft** [comment]
there are tile ids and tile GIDs.  internally, pytmx uses the same GIDs that tiled uses.  the GID is not a property, it is a numeric value that references a single tile image to a tile coordinate.  tile properties dicts are also mapped to GIDs.  to rewrite the the layer data, changing the properties will have no effect.  take a look at the documentation for more details if you are still unclear https://doc.mapeditor.org/en/stable/reference/tmx-map-format/
all this is helpful in knowing if you experiment with modifying the data.  with all that in mind, you can access the specific layer that has the tile you want to change and change the value to 0.  `tmxdata.get_layer_by_name('walls')[y][x] = 0`  something like that will do what you want.  changing the tile properties dictionary will change the properties for all tiles, not the single on that you intend to remove.
the `set_properties` function is really just for internal use.

**Comment by MaximumCDawg** [comment]
In reading your documentation -- and reading the pytmx code -- I can't really understand how tiles are stored in TiledTileLayer. I dont see a list of internal variables or methods, for example. I don't _think_ that TiledTileLayer is just a 2-d array of tile objects... or at least, if it is, it doesnt seem to act like one. 

When I use your suggestion, for example, it tells me: "TypeError: 'TiledTileLayer' object is not subscriptable" which I understand to be telling me that I can't index this object. 

Sorry if these are dumb questions!

**Comment by bitcraft** [comment]
TiledTileLayer has an attribute called "data", which really is just a 2D array of integers, not objects.  They are GIDs, which is what the TMX map format uses.  You don't change "the third element" of anything.  Change TiledTileLayer.data[y][x] to 0, 1, anything else.
