### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by dotlambda** [bitcraft/pytmx#147]
Especially for distributions, it would be nice if releases showed up in https://github.com/bitcraft/pytmx/releases.

**Comment by bitcraft** [comment]
thats a reasonable suggestion.  added release for 2.25, ill try to stay on top of tagging new releases as well.

**Comment by dotlambda** [comment]
Thank you!

**Comment by oxzi** [comment]
Thanks for still maintaining pytmx! But could you please continue tagging releases in git? The latest version, 3.32, is missing a tag. Thanks.
