### ISSUE TITLE
Tile rotation not existing

### ISSUE THREAD

**Issue by NeoCortex97** [bitcraft/pytmx#149]
I have a tileset, that needs some tiles to be rotated for up, dowm, left and right.

I see that the rotated tiles get different gids, but I cannot find a way to rotate the tiles that need to be rotated. Relying on the gid seems not like a good thing to me.

**Comment by bitcraft** [comment]
What graphics library are you using?  In Pygame, the tile images should be rotated for you, and there is no need to transform them.  Other frameworks will need changes.  You can use the "custom image loader" feature to customize how rotations are handled:
https://github.com/bitcraft/pytmx/blob/master/pytmx/util_pygame.py#L87

> Relying on the gid seems not like a good thing to me.
pytmx is a map loader, primarily.  It can be used for rendering, or handling tile rotations, but you don't have to use it like that.  Using GID for rotations is what Tiled does, and pytmx is pretty close to the same format, internally.

**Comment by bitcraft** [comment]
pytmx translates the gid.  the fact that rotation is encoded into the value is a design from Tiled, not pytmx.  they are really an implementation detail that is shared with tiled and should not be relied on.
rotation should be handled by the loader.  i just tested the latest code and have found no regressions and the tiles are rotated as expected.

@Mattlau04 I tried the code you provided and rotation works fine.  what version of pytmx are you using?
```python
        group = pygame.sprite.Group()
        class Tile(pygame.sprite.Sprite):
            def __init__(self, x, y, image):
                super().__init__()
                self.x = x
                self.y = y
                self.image = image

        for x, y, image in layer.tiles():
            tile = Tile(x * tw, y * th, image=image)
            group.add(tile)

        # later in the code
        for tile in group:
            surface.blit(tile.image, (tile.x, tile.y))
```
![image](https://user-images.githubusercontent.com/556711/132542886-ff9feb03-1291-4390-805b-f3dc602e4066.png)
