### ISSUE TITLE
pygame dependency

### ISSUE THREAD

**Issue by HuxyUK** [bitcraft/pytmx#157]
Hi!
Can I just check, is the library usable without **pygame**? When I try to import it, it fails due to pytmx attempting to import pygame. 

Thanks

**Comment by bitcraft** [comment]
yeah it should be.  what version of python are you using?  and the code?  the "try to import pygame, but don't fail if not available" thing hasn't always worked well.

**Comment by HuxyUK** [comment]
I'm using a Python 3.10 and PyTMX 3.30.
On line 34 in pytmx.py there's an import pygame statement. I I removed it out of interest, and I can see that PointLike is directly referencing a pygame.Vector2. 

```python
PointLike = Union[Tuple[int, int], pygame.Vector2, Point]
```

I followed the code in the README.md but as soon as I try to import ptymx the error is generated.

**Comment by bitcraft** [comment]
Ok. So it’s failing because of the type annotations.  I’ll take a look at
it today. Thanks for the additional info.

**Comment by bitcraft** [comment]
seemed like a simple fix.  should be working now.  there is an error message still, since the primary users of pytmx are pygame users and in the past i used to get a lot of questions about it not working...when pygame wasn't installed.  maybe the message can be removed in the future.  let me know.

**Comment by HuxyUK** [comment]
Good news! I Just tested and I was able to load the map with no pygame issues. 

>  used to get a lot of questions about it not working...when pygame wasn't installed

Honestly, it's not an error per se, but I totally understand where you're coming from. As long as it doesn't impact functionality, it's a bit of a moot point. 

I'll close the ticket and let you know if I get any more issues. Thanks for the quick turn-around!
