### ISSUE TITLE
rotation and flip for objects in pygame

### ISSUE THREAD

**Issue by AntoineGlacet** [bitcraft/pytmx#158]
Not sure where to post this, but when trying to work with objects, the rotation and flip is very hard to handle.
After extensive research, the best I could achieve was to just avoid using rotation and flip altogether.
I think it would be a great feature to be able to have seamless integration of rotation and flip from pytmx to pygame or a documented work around in pytmx documentation

**Comment by bitcraft** [comment]
hi, thanks for opening the issue.  what specifically is the problem?  pytmx has its own quirks with rotation/ flipping, etc, so pytmx inherits them.  that said, it is supported in pytmx.  for example, tiles are flipped and rotated as needed.  objects with points are also supported if you use the `apply_transformations` method.  it will return the points after...applying the transformations such as rotation.  its not well tested though, and there are sure to be cases that i haven't tested with, but it might be enough for you to get working (or open an issue or PR with a fix).

here is an example of it in use:
https://github.com/bitcraft/pytmx/blob/master/apps/pygame_demo.py#L124-L125
