### ISSUE TITLE
Flipped version of the tile image can't be loaded

### ISSUE THREAD

**Issue by Grimmys** [bitcraft/pytmx#166]
Context:

I have two objects in my object layer, that have the same image but one should have it vertically flipped.

At the end, when loading the objects of this layer, I see that only one of them as an image correctly loaded as pygame Surface, the other one is None.

I would expect to be able to get the flipped version of the image somehow (maybe I'm missing something).

The concerned TMX data:

```xml
<objectgroup id="5" name="dynamic_data">
  <object id="14" type="objective" gid="1099" x="0" y="96" width="32" height="32">
   <properties>
    <property name="mission" value="main"/>
    <property name="walkable" type="bool" value="true"/>
   </properties>
  </object>
  <object id="103" type="objective" gid="1073742923" x="0" y="128" width="32" height="32">
   <properties>
    <property name="mission" value="main"/>
    <property name="walkable" type="bool" value="true"/>
   </properties>
  </object>
 </objectgroup>
```

First object has the original image, and the second the flipped version.

At the end, PyTmx loads the objects as such:

![pycharm_loaded_objects](https://user-images.githubusercontent.com/25286578/164923264-58ed6784-11df-4a6a-92f8-e7eec9e6b392.png)

**Comment by bitcraft** [comment]
fixed here 5a3a39a2902868401569c6a36aa8e68209fb5a8b
