### ISSUE TITLE
Mass replace type with class: Tiled v1.9

### ISSUE THREAD

**Issue by JaskRendix** [bitcraft/pytmx#170]
Hello, I wanted to share this: [The new map version (1.9) will mass replace type with class.](https://github.com/mapeditor/tiled/issues/3492)

**Comment by joereynolds** [comment]
There's no need for this, it was quickly reverted in 1.10 as it broke a lot of things

https://www.mapeditor.org/2023/03/10/tiled-1-10-released.html

**Comment by JaskRendix** [comment]
@joereynolds thanks!
