### ISSUE TITLE
how to break and place tiles with pygame

### ISSUE THREAD

**Issue by FowluhhPPTX** [bitcraft/pytmx#172]
i really need help with this

**Comment by FowluhhPPTX** [comment]
im making a minecraft clone and im using a tilemap for blocks

**Comment by JiffyRob** [comment]
I don't think this would be pytmx related at all.  Assuming you have a class for individual tiles, all you would have to do is just create more tile sprites and add then to your main sprite group.  To remove, just call sprite.kill().  If you have single sprite per layer, then you can do blits/erases to that sprite's surface.  As for saving results, pytmx has no save feature, so you would either have to save it using a different library, or use your own save format (eg. a list of [x, y]: terrain type dict
