### ISSUE TITLE
TiledImageLayer.image returns the wrong image

### ISSUE THREAD

**Issue by nmfm** [bitcraft/pytmx#183]
When loading the image for a TiledImageLayer, `layer.gid` is set to the "registered" gid.

https://github.com/bitcraft/pytmx/blob/7af805bc916e666fdf7165d5d6ba4c0eddfcde18/pytmx/pytmx.py#L699-L700

But the `image` property of TiledImageLayer tries to fetch the image from `self.parent.images[self.gid]`, and
that images array is indexed by the real_gid, not the registered one, so the wrong image is returned.

https://github.com/bitcraft/pytmx/blob/7af805bc916e666fdf7165d5d6ba4c0eddfcde18/pytmx/pytmx.py#L1628

I could try to make a PR for this, just not sure what's the best solution, either

`layer.gid = real_gid`  on the loader 

or returning `self.parent.images[self.parent.tiledgidmap[self.gid]]` on TiledImageLayer.image.

**Comment by bitcraft** [comment]
interesting.  the images array should be indexed by the "registered" gid, not the real one.  are you able to get the right image if you make that change?  i haven't noticed this problem before.

**Comment by nmfm** [comment]
Unfortunately I didn't save a copy of the map where this was happening and now I can't reproduce it.

I'll re-open it if I ever come across it again, and will post the assets. Who knows, maybe it was just an hallucination :man_shrugging:
