### ISSUE TITLE
Exception thrown for infinite map size lacks a message (pytmx.py, line 1426)

### ISSUE THREAD

**Issue by TritionGames** [bitcraft/pytmx#191]
Using an infinite tilemap isn't supported and so it raises an exception, but all the error message displays is simply "Exception"

https://github.com/bitcraft/pytmx/blob/7af805bc916e666fdf7165d5d6ba4c0eddfcde18/pytmx/pytmx.py#L1426

**Comment by JaskRendix** [comment]
I have updated the def in my open PR: https://github.com/bitcraft/pytmx/blob/d574e0975c9e78292edc321c5030410919092a3d/pytmx/pytmx.py#L1426
