### ISSUE TITLE
util_pygame not working?

### ISSUE THREAD

**Issue by Octaviorios** [bitcraft/PyTMX#55]
Hello and thanks for your hard work! I've been tring to use a function from the util_pygame module and it keeps on giving me this error: 

AttributeError: 'module' object has no attribute 'util_pygame'

Am i doing something wrong?

**Comment by bitcraft** [comment]
What version of python and pytmx are you using?

**Comment by Octaviorios** [comment]
Python 2.7.10. Not sure how to check version for PyTMX, but if it's the one
in the changelog txt file it should be 3.20.x

2015-06-06 14:20 GMT-03:00 Leif Theden <notifications@github.com>:

**Comment by bitcraft** [comment]
Please paste or provide a link to the file that you are having trouble with.

**Comment by Octaviorios** [comment]
Here it is on dropbox:
https://www.dropbox.com/s/53jm8ggbpfgt3ye/mainconhero.py?dl=0

2015-06-06 15:53 GMT-03:00 Leif Theden <notifications@github.com>:

**Comment by bitcraft** [comment]
Thanks for the link.  I cannot find where you are attempting to use
'pytmx.load_pygame' in the included file, so I cannot help you there.  I
see you've tried to use pyscroll as well.  If you want the pygame scrolling
layer, please follow the example 100% on the pyscroll page, or look at the
tutorial game that is included with it for more help.

**Comment by mkli90** [comment]
Hm, if you want to you can have a look in here too: https://github.com/mkli90/tekmate/blob/master/tekmate/configuration.py 
That's how I use the util_pygame and it's working pretty good for me.

**Comment by Octaviorios** [comment]
Thanks a lot! Im going to have a look at it as soon as i can.

**Comment by Octaviorios** [comment]
Sorry for the delay. After checking out your code i could put the "load_pygame" thing to work by adding:

                  from pytmx.util_pygame import load_pygame

at the begging and then i use it like this:
 
                  datatmx=load_pygame("resources/tiledmap.tmx")

I might also clarify that i have created this variable at the beginning and i'm not really sure what is the difference between the two.

                  mapatmx=pytmx.TiledMap("resources/tiledmap.tmx")

Anyway, the game launches with no errors, it works perfectly fine, but of course the hero still walks over every image because i can't figure out how to make the build_rects method work, yet. This is how i tried to create the rects:

                  build_rects("resources/tiledmap.tmx", 3, "collision", 88)

which gives me the error:    AttributeError: 'str' object has no attribute 'tilesets'.
This led me to think that i should'nt be using a str type of value, so i tried using my pytmx.TiledMap variable i wrote above:

                 build_rects(mapatmx, 3, "collision", 88)

which just gives me this error:  AttributeError.

So, i'm clearly not understanding something here. I can't figure out how to use the build_rects thingy. If any of you could link me to a tutorial or something that would be great, because it's pretty much the only thing stopping me to continue with my little project. Thanks a lot.

**Comment by bitcraft** [comment]
Please include your full tracebacks.

**Comment by bitcraft** [comment]
I've found a bug.  build_rects is pretty experimental, and wasn't used for a long time and was never part of my tests....so I missed it.  You can use it, but I will probably change it sometime in the future, since right now it is awkward to use.

I've updated the docs.  Please just use a string name for the Tileset and map Layer.  For example:
    rects = build_rects(tmx_map, "Grass and Water Layer", "Grass and Water Tileset", 18)

Finally, I've found that using Tiled Objects is easier that tiles for collisions.  Just add a new layer called "Collisions" and draw boxes over the areas that you want as collisions.  See this code to load the objects as Rects:
https://github.com/bitcraft/pyscroll/blob/master/tutorial/code/quest.py#L110-L114
https://github.com/bitcraft/pyscroll/blob/master/tutorial/code/quest.py#L196-L198

Thanks for the bug report!

**Comment by Octaviorios** [comment]
Awesome! I'll take a look at both ways of doing collisions. I'm so glad you could help me, thanks a lot!

**Comment by bitcraft** [comment]
You're welcome.  :)
