### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by cinatic** [bitcraft/PyTMX#56]
Hello,

great Editor and work! Could you provide also git hub versions from time to time, so that this can be easy managed by repository systems to notify people if there are new "versions"?

This would be great!

**Comment by bitcraft** [comment]
Just fyi, this is the the Tiled editor, this is some python code to load the maps from the Editor for use with python.

**Comment by cinatic** [comment]
I don't understand, yes it is.

I am maintaining the package of this editor in ArchLinux. 

To have versions (here in github under the tab versions) would be really useful to indicate to the people that there is something new when they update their packages. Otherwise i have to make a pull from time to time and add some kind of version (timestamp).

Just think about it, this is very common, but i know time is usually rare :P

https://help.github.com/articles/creating-releases/

Sorry my english is not that perfect.

**Comment by cinatic** [comment]
sorry i mean the section/tab "Releases" not "Versions"

https://github.com/bitcraft/PyTMX/releases

**Comment by cinatic** [comment]
ah sorry of course it is not an editor i was mistaken, nontheless a very nice lib!

**Comment by bitcraft** [comment]
A few people have confused this github repo with the main Tiled Map Editor repo, so I wanted to make sure you know that I am not Bjorn, and just maintain a python library…not the editor.  Do you package pytmx for Arch?  I update versions on pypi, if that helps you at all.  I’ll look into github releases.
