### ISSUE TITLE
Getting Attribute Error when running getObjects()

### ISSUE THREAD

**Issue by DrevanTonder** [bitcraft/PyTMX#67]
```
for object in tmx_data.getObjects():
	properties = object.__dict__
	if direction == "left":
		if properties["name"] != "dirtBlock":
				player.rect.x -= 32
	if direction == "right":
		if properties["name"] != "dirtBlock":
			player.rect.x += 32
```
when I run this part of code in my program I get
```
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    main()
  File "main.py", line 50, in main
    for object in tmx_data.getObjects():
  File "build\bdist.win32\egg\pytmx\pytmx.py", line 190, in __getattr__
AttributeError
'''

**Comment by bitcraft** [comment]
Thanks for the the issue report.  A long time ago, when I wrote pytmx, I used camelCase method names.  A few years ago, I change the camelCase names to under_score to be more 'pythonic' and just look a bit nicer.  You must be using an old version of pytmx.  Please make sure you are using the most current one.  You will notice that getObject, getTileProperties, etc have different names.  Sorry about the confusion.  I wish I had done the names right the first time!

The most recent pytmx is available through pypi, or here in the repo.  You'll have access to new features like animated tiles, image layers (and more!) plus python 3 support.  Thanks for using pytmx.

http://pytmx.readthedocs.org/en/latest/pytmx.html

```python
for object in tmx_data.objects:
    if direction == "left":
        if object.properties["name"] != "dirtBlock":
                player.rect.x -= 32
    if direction == "right":
        if object.properties["name"] != "dirtBlock":
            player.rect.x += 32
```

**Comment by DrevanTonder** [comment]
Thanks.
