### ISSUE TITLE
Expecting TiledObject but getting a tuple

### ISSUE THREAD

**Issue by Regner** [bitcraft/PyTMX#68]
Hey,

When I do the following:
```python
tmx_data = load_pygame('untitled.tmx')
for test in tmx_data.get_layer_by_name('base'): print type(test), test
```

I get:
```
<type 'tuple'> (63, 19, 1)
```

Based on the readme I expect that to return TiledObjects but it is not. Am I doing something wrong?

I have:
* pygame 1.9.1
* pyscroll 2.16.1
* PyTMX 3.20.14

**Comment by bitcraft** [comment]
Depends on the layer. If "base" is a tiled layer, then it will iterate tile
data (x, y, gid). Object layers will iterate tiled objects.

**Comment by Regner** [comment]
My apologies, incredibly new to Tiled and didn't understand the difference in the two layer times. Ignore this! :)
