### ISSUE TITLE
Handling of Terrains and Terrain Properties?

### ISSUE THREAD

**Issue by Remusforte** [bitcraft/PyTMX#73]
Does PyTMX handle the "terrain" info saved in the .tmx file, and if so where do I find it?
Here for example is a snip from a .tmx file I created with Tiled. In this case, I have a set of "terrains" defined, each with custom properties as shown:
![image](https://cloud.githubusercontent.com/assets/16418812/12460244/d328ec40-bf80-11e5-87a9-6fa524e6ef52.png)
Where are these custom properties stored in a PyTMX object... I've searched and have yet to find any mention of "terrain" or the properties associated with them...
Help? Thanks!

**Comment by bitcraft** [comment]
Hello again Remusforte.  Pytmx doesn't load terrain information as it basically defines a 'brush' to paint tiles with.  If you could, paste the tmx data somewhere (gist?) so that I can see what you are doing with it.

**Comment by Remusforte** [comment]
Thx for the quick reply! Recall from last conversation that you'd suggesting using Custom Properties to identify tiles in the map. In Tiled, I use the Terrains feature to create easily identifiable tiles for pick/place into the map; I find it easier for users to understand the individual Terrain pick-lists vs looking at the entire TileSet image and picking off that. I then attached Custom Properties to each Terrain tile I had identified. So the snip above shows the output, with the terrain names and their associate properties listed. I can see pretty easily how I can use PyTMX to extract the tiles being used in the map, but I was hoping to use the Terrain info embedded in the .tmx to then grab the Custom Properties associated with them. Sounds like this info doesn't come in...

Plan B (about to try) is to set the Custom Properties in the TileSet itself (I did this as a test after our last chat, and it worked). THEN define Terrains for those same tiles. I'm hoping the USER can pick off the Terrain pick-lists, but when saved, the Custom Properties get grabbed and saved from the TileSet, which I know is read in by PyTMX. I'll update if that works...

**Comment by bitcraft** [comment]
Please post the entire map in text form somewhere and link back here.  Optionally, you can email it to me: leif.theden@gmail.com.  I won't comment further until I see an example map.  No screenshots.  Thank you for understanding.

**Comment by Remusforte** [comment]
I believe issue resolved. My Plan B worked: rather than defining the Custom Properties in the Terrain area of Tiled, I used the Tileset area. Then I defined Terrains in Tiled so the User would have a clear pick-list (palette). When I use those Terrain picks to make a map, then save it, the underlying Custom Properties in the TileSet are getting saved into the .tmx file. And PyTMX is picking them up. So I get the best of both worlds: handy "palette" for the User via the Terrains feature, but Custom Properties read in through PyTMX. :-) 

I can send the (not working) map text via email, but the original has been changed as I played with things, and now throws an exception when I try to load it in PyTMX; perhaps confused by a mix of terrain and tile definitions as I experimented. Probably not very useful. Let me know if you still want it and/or the latest version that is now working properly.

Thanks again for taking the time to respond.

**Comment by bitcraft** [comment]
I don't mean to repeat myself here.  I'm glad that you have a work around, but if you feel that the properties in the terrain definitions are worth using, then I need a sample map.  I don't have time to build maps, but I'm willing to make new features if I get a map to work with.
So, email me the map if you feel that proper terrain support is useful and leave this issue up, or close it.

**Comment by Remusforte** [comment]
The workaround is perhaps the best solution for me at this point. Now that I have the Custom Properties assigned to the TileSet, I can very easily use PyTMX to query: tiled_map.get_tile_properties(x,y,layer) and instantly extract what is at any location on the map. That's all I need at this stage. If I later find something missing that the Terrain Custom Properties would make necessary, I will open a new ticket. Thanks very much again!
