### ISSUE TITLE
Support Terrains

### ISSUE THREAD

**Issue by mgrazebrook** [bitcraft/pytmx#75]
Tiled and the TMX format support Terrains. I couldn't see how to do this in pytmx so I modified a copy of your library to support them. If you think this would be a useful addition, please let me know how I should proceed. 

My implementation provides:
class TiledTerrain (the obvious implementation based on the tiled spec)
TiledTileLayer.terrain(self, x, y, corner)

It works for me but would probably need further work to be part of the library, for example:
I wrote it in Py 3.4
Only tested for one simple case ("Desert")

If you want to email me, my email is my name with at in the middle and dot com on the end.

Michael Grazebrook

**Comment by bitcraft** [comment]
Thanks for your contribution.  I've been getting more requests for terrain support, I suppose now I should do something about it.  I'd be happy to accept patches or pull requests, and I can clean it up and test it against the my test maps and python 2.7.  leif.theden@gmail.com
