### ISSUE TITLE
Modifying loaded data

### ISSUE THREAD

**Issue by ri0t** [bitcraft/PyTMX#76]
Is there a clean way to modify tiles of an already loaded map?
I'd like to add "terraforming" to my engine ;)

**Comment by bitcraft** [comment]
Yes.  Lookup the GID/GUID of the tile that you want to use as a replacement, then set the layer data to that number.

It is a bit awkward to do because pytmx wasn't designed as a level storage format, just to load data from the tmx files and use in other data structures.

```python
layer = tmx_data.layers[0]
layer.data[y][x] = new_tile_gid
```
