### ISSUE TITLE
Remove dependency on mask module

### ISSUE THREAD

**Issue by bitcraft** [bitcraft/PyTMX#78]
Removing this dependency will make it easier to support pygame forks without the mask module.  Comments?

**Comment by DaveMcGr** [comment]
I found that by completely replacing the `smart_convert` function in `util_pygame.py`  with code below:

`tile = original.convert_alpha()`
`return tile`

Allows me to remove the mask submodule altogether and even use Pygame_SDL2, though I can't get it to run properly on Android (See the issue https://github.com/renpy/rapt/issues/5)

Correct me if I'm wrong but, is the entire `smart_convert` function only used to improve efficiency.
I tested this on a few games I found around the internet, and all seemed well.

**Comment by Connor124** [comment]
I found that by completely replacing the `smart_convert` function in `util_pygame.py` with code below:

`tile = original.convert_alpha()`
`return tile`

Allows me to remove the mask submodule altogether and even use Pygame_SDL2, though I can't get it to run properly on Android (See the issue renpy/rapt#5)

Correct me if I'm wrong but, is the entire smart_convert function only used to improve efficiency.
I tested this on a few games I found around the internet, and all seemed well.

**Comment by bitcraft** [comment]
You are correct, smart convert is only used to improve rendering speed by determining the optimal surface format.  The mask module is used to determine if there are transparent pixels and can do that really quickly.  A work around may be to use a slower method if mask is not available.  Thanks for checking it out and testing.

**Comment by Connor124** [comment]
No problem, all I did to start was hard code the `px`, the moved from there.

**Comment by bitcraft** [comment]
I've included a small check for the mask module and it should work with pygame_sdl2 now.  It will simply convert_alpha the surface if it fails to get a mask.
