### ISSUE TITLE
does this depend on pygame?

### ISSUE THREAD

**Issue by MRFaria** [bitcraft/PyTMX#79]
When I import pytmx I get the message:
`cannot import pygame (is it installed?)`

But pygame is not listed as a dependency anywhere on the requirements page, is this an erroneous message?

**Comment by bitcraft** [comment]
No it is not a requirement. Pytmx doesn't require a graphics lib. The
message is there for people who have issues with imports or don't have
pygame, but think pytmx broke something (happens enough for me to add the
message).

It can be ignored or edited out of it bothers you.

**Comment by MRFaria** [comment]
Alright, I'll just ignore it as everything seems to be working correctly. Great project btw, I was able to integrate it fairly easily with PyQt5 image loading

**Comment by bitcraft** [comment]
Awesome, glad it worked out for you.  Was the image loader interface
difficult to figure out?  I wonder sometimes, because some people might not
be familiar with returning functions/closures.

**Comment by MRFaria** [comment]
I think it is fairly intuitive, the example is that is included in the docs basically does it.

`class QtTileMap(pytmx.TiledMap):
    def __init__(self, fileName, scene):
        super().__init__(fileName, image_loader=self.qtImageLoader)
        self.scene = scene

    def qtImageLoader(self, filename, colorkey=False, **kwargs):
        srcImage = QPixmap(filename)

        def extract_image(rect, flags):
            x, y = rect[0], rect[1]
            width, height = rect[2], rect[3]
            tileImg = srcImage.copy(x, y, width, height)
            return tileImg

        return extract_image
`

**Comment by bitcraft** [comment]
Thank you @MRFaria.  I'm going to close this issue, but feel free to comment if you want to.
