### ISSUE TITLE
Tileset cropping and storing None values

### ISSUE THREAD

**Issue by shellbotx** [bitcraft/PyTMX#80]
I have an issue where one of my tilesets is being cropped by the PyTMX. I am currently using 3 tilesets and only the final one is experiencing issues.

I am loading using the pygame loader, but I run into the same issue with a custom loading function (that also relies on pygame). Prior to switching to PyTMX there was no issue with tile rendering.

The last 3 rows of my tileset are not loading correctly. They are represented in `TiledMap.images` as `None` elements.

**Comment by bitcraft** [comment]
That's odd. Do you mind sharing your map and tileset images?

**Comment by bitcraft** [comment]
BTW, if the tiles are never used in the map, they will not be loaded unless you pass load_all_tiles=True.  Unused tiles will have None as a reference in the tiles list.  Rarely, oddly shaped tileset images, such as having extraneous graphics, logos, etc, may load improperly.  I'd have to see the map and images to verify and test.

https://github.com/bitcraft/PyTMX/blob/master/pytmx/pytmx.py#L231-L236

```python
# load unused tiles into memory
tmx_data = util_pygame.load_pygame(filename, load_all_tiles=True)

# same as above, but using custom image loader
tmx_data = pytmx.TiledMap(filename, loader_function, load_all_tiles=True)
```

**Comment by shellbotx** [comment]
I have fixed it. The height of the tileset was different than the height in the TSX file. I corrected the error and everything is working correctly now.
