### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by Filfire09** [bitcraft/pytmx#82]
I was trying to use pytmx version 3.20.17 and while running code I've been getting this error

Traceback (most recent call last):
  File "/Users/fpoadmin/Desktop/pygameimages/camera.py", line 17, in <module>
    gameMap = pytmx.load_pygame('images/map RPG3.tmx')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytmx/util_pygame.py", line 116, in load_pygame
    return pytmx.TiledMap(filename, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytmx/pytmx.py", line 285, in __init__
    self.parse_xml(ElementTree.parse(self.filename).getroot())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytmx/pytmx.py", line 319, in parse_xml
    self.add_layer(TiledImageLayer(self, subnode))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytmx/pytmx.py", line 1110, in __init__
    self.parse_xml(node)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytmx/pytmx.py", line 1129, in parse_xml
    self.source = image_node.get('source')
AttributeError: 'NoneType' object has no attribute 'get'

# code
There is my code:

import pygame
import pytmx

pygame.init()

display_width = 800
display_height = 800

white = (255, 255, 255)

gameScreen = pygame.display.set_mode((display_width, display_height))
pygame.display.set_caption('2d Game')
clock = pygame.time.Clock()

gameMap = pytmx.load_pygame('images/map RPG3.tmx')

 def game_loop():
     gameExit = False
     while not gameExit:
         for event in pygame.event.get():
             if event.type == pygame.QUIT:
                gameExit = True

   for layer in gameMap.visible_layers:
         for x, y, gid, in layer:
             tile = gameMap.get_tile_image_by_gid(gid)
             gameScreen.blit(tile, (x * gameMap.tilewidth,
                                   y * gameMap.tileheight))
     pygame.display.update()
     clock.tick(30)

 game_loop()
 pygame.quit()

The code did not really matter because I tried it with other codes and it would give the same error. 

Please help me.

**Comment by bitcraft** [comment]
Can you attach the tmx file you are using?

**Comment by Filfire09** [comment]
Unfortunately, this site does not support TMX file I can't attach it....

**Comment by bitcraft** [comment]
Ok. You can use a pastebin. I'm not sure but it looks like maybe it can't
find an image file. Posting the tmx will help clarify that.

**Comment by Filfire09** [comment]
I'm sorry what's a pastebin ? ;/

**Comment by bitcraft** [comment]
http://dpaste.com
Use this site to copy the contents of the tmx file

**Comment by Filfire09** [comment]
[map RPG3.tmx.zip](https://github.com/bitcraft/PyTMX/files/1033910/map.RPG3.tmx.zip)
Well actually I'll send you this zip file tell me if it works.

**Comment by bitcraft** [comment]
Thanks that worked fine. I've never seen Tiles do this, but there is an
image layer with no image. I can make a fix for it sometime in the next few
days.

If you just want it to work now, remove the layer called "Calque d'image
1", or give it an image and try again.

**Comment by bitcraft** [comment]
@Filfire09 has your issue been solved?

**Comment by Jonatan00x** [comment]
As for me deleting empty object layer solved the problem. 
I have got an attribute error raised in __getattr__ in TiledElement class.
Now it works.
