### ISSUE TITLE
Objects' dimensions are overwritten during the XML parsing

### ISSUE THREAD

**Issue by maxfish** [bitcraft/PyTMX#86]
The parse_xml method of TiledMap is currently overwriting the objects' dimensions with the tileset's dimensions: 
```
if self.invert_y:
    o.y -= tileset.tileheight
o.height = tileset.tileheight
o.width = tileset.tilewidth
```
It is possible to notice this whenever the dimensions of an object are different from its tileset's ones.
In that case, also the invert code doesn't work as expected.

I've temporarily fixed the issue by storing the tileset's dimensions in other variables, and by using the object's height when inverting Y:
```
if self.invert_y:
    o.y -= o.height
o.tileheight = tileset.tileheight
o.tilewidth = tileset.tilewidth
```

**Comment by bitcraft** [comment]
This block of code handles objects with a tileset GID.  Normally, GID objects do not have dimensions set, instead they use the tileset dimensions.  This was a while ago, I'm not sure if this has changed.  Do you have an issue with a map produced by Tiled?  Or was this just a code review sort of thing?

**Comment by maxfish** [comment]
Hey Leif, I have an issue with a map produced by Tiled (v0.18.0).
Here is a Gist able to reproduce it: https://gist.github.com/maxfish/4764d60fd56d780b159cc4153c7d8852

This is the image I've used (texture.png):
![texture](https://user-images.githubusercontent.com/1917764/28129584-250a6d2a-6734-11e7-9c9d-6108dfbbc56d.png)

And this is how the map looks like in Tiled:
![screen shot 2017-07-12 at 18 58 07](https://user-images.githubusercontent.com/1917764/28129612-3f60c804-6734-11e7-8fbc-1a2bd9507d04.png)

As written above, there is no way (that I know) to access the width and height of those objects from the code.

**Comment by bitcraft** [comment]
It should be accessible from just the object.height and object.width

**Comment by maxfish** [comment]
Yes, exactly. To be able to do that you would need the change I posted on my first message.
If you look at the test code, I'm printing what I get from object.width and object.height, for both objects they are 128x128.
One of the two should be 256x128.

**Comment by bitcraft** [comment]
It seems Tiled will now includes the height and width all the time.  In the past, it would not include that data, meaning it was necessary to use the tileset data.  I can have a fix shortly.

**Comment by maxfish** [comment]
Cool, thanks!

**Comment by bitcraft** [comment]
Pushed a fix.  You can try the repo or pip.  Let me know if that works for you.

**Comment by maxfish** [comment]
Tried it, but it requires a small change on the invert_y code. I'm going to add a comment there.

**Comment by bitcraft** [comment]
Just noticed that.  Fixed.

**Comment by maxfish** [comment]
Great! v3.21.1 fixes the issue
