### ISSUE TITLE
Crash when loading image from raw XML

### ISSUE THREAD

**Issue by Gustra** [bitcraft/PyTMX#87]
If a map is loaded using the from_xml_string and the map contains an image reference, then pytmx.py crashes because the filename is not defined:

```
    self.tmx_map = pytmx.TiledMap.from_xml_string(kwargs['tmx'])
  File "<...>/venv/lib/python2.7/site-packages/pytmx/pytmx.py", line 164, in from_xml_string
    return cls().parse_xml(ElementTree.fromstring(xml_string))
  File "<...>/venv/lib/python2.7/site-packages/pytmx/pytmx.py", line 359, in parse_xml
    self.reload_images()
  File "<...>/venv/lib/python2.7/site-packages/pytmx/pytmx.py", line 417, in reload_images
    path = os.path.join(os.path.dirname(self.filename), source)
  File "<...>/venv/lib/python2.7/posixpath.py", line 122, in dirname
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

Here is the relevant part of the map XML:

```
<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0" tiledversion="1.0.1" orientation="orthogonal" renderorder="right-down" width="40" height="32" tilewidth="32" tileheight="32" nextobjectid="13">
 <imagelayer name="Image Layer 1">
  <image source="../../assets/images/testmission.png" width="1280" height="1024"/>
 </imagelayer>
</map>
```

I don't know the innards of pytmx, but one solution would probably be to add a second argument to the `from_xml_string` and `parse_xml` methods, where a path can be given representing the file location.

**Comment by bitcraft** [comment]
I might be mistaken, but I believe that relative file paths like this are
relative to the tmx map file. Is that image file location relative to the
map file correct? Could you link or paste the path that is sent to the
loader? I have a feeling that Python std lib is unable to determine the
absolute paths for the resource.

**Comment by Gustra** [comment]
There is no file involved when using the `pytmx.TiledMap.from_xml_string()` class method:
```
def from_xml_string(cls, xml_string):
    ...
    # A TiledMap is created, cls(), with no arguments to the constructor making self.filename None:
    return cls().parse_xml(ElementTree.fromstring(xml_string))
```
`parse_xml()` is called on the instance, and that method calls `reload_images()`:
```
    self.reload_images()
```
And finally, `reload_images()`, uses self.filename:
```
            # At this point self.filename is still None, and os.path.dirname() rolls over:
            path = os.path.join(os.path.dirname(self.filename), source)
```
I am going to try to work around this problem by adding a file name argument or use an image_loader function.

**Comment by bitcraft** [comment]
Good point. I think that the correct solution would be to pass a path,
"/home/gunnar/maps") perhaps "resource_root" or "document_root", (instead
of a file name) when loading xml maps. I haven't run across this in
testing, since I've navel used relative paths for resources in this manner
before. Thank you for raising this issue. Patches are welcome, or leave
this open and I'll look into it next week.
