### ISSUE TITLE
Accessing unused tileset's tile properties

### ISSUE THREAD

**Issue by groug** [bitcraft/PyTMX#88]
Hi,

It seems that only the used tiles of a tileset are loaded, when I load a tilemap.
I used a property called "flag" on some tileset's tiles and I have 2 layers in a tilemap: 1 with what I want to draw, and another layer that is used to describe which tiles of the first layer are replacable.
Now, what I want to do is find all the tiles in my tileset that have a the same property "flag", but since only the used tileset's tiles are loaded, I can't access the others.

Any idea?

**Comment by bitcraft** [comment]
Try passing "load_all_tiles=True" to the loader or constructor.

https://github.com/bitcraft/PyTMX/blob/master/pytmx/pytmx.py#L247

**Comment by groug** [comment]
Hi,

Thanks for the tip, I didn't see it (btw the requirement argument is load_all, despite what the comment is saying)
It doesn't work.
https://github.com/bitcraft/PyTMX/blob/master/pytmx/pytmx.py#L394
map_gids returns an empty list when it's not used, and a few lines below, it checks if it has returned None if it's not used.
And if the check is fixed, then at L407 it crashes because self.images has not been updated.
And L827, only used tiles' properties are stored.

As a temp fix I'm loading a tmx with all the tiles drawn into it, and that's ugly :/

**Comment by bitcraft** [comment]
Hmm yeah that's not optimal.  pytmx is beginning to show its age..  its been a long time project that I used, and opened it up for others, so it is a bit quirky.  

Question for you...  Do you see much value in the default behaviour of ignoring unused tiles?  Suppose that properties worked in spite of that.  I've been considering changing the default behaviour to to load all tiles.

In the mean time, I'll investigate this problem.  It would be helpful to me if you could share the contents of the TMX map file.

Thank you!

**Comment by groug** [comment]
Hi,

Maybe it's aged, but I like it :)
Personally, ignoring unused tiles should not be the default behaviour, but maybe it's because I want more that the average Joe.
But loading all the tiles only means loading rect info and properties, if they were loaded by default, that wouldn't increase memory that much, so I'm all in favor of that!

I'm not the only one working on the game, so I can't really share the tmx map, but I can recreate the case. I'll try to do that asap, thanks!

**Comment by bitcraft** [comment]
Thanks for sharing this.  Feel free to delete your post now, I've downloaded it and won't share it.  I also agree that the default behaviour should be changed to load all tiles.  I've had this come up a few times.  I'll look at the map tonight.

**Comment by bitcraft** [comment]
@groug I've fixed the problem of tile properties not loading with 'load_all_tiles' is specified.  I've thought about your use case a bit.  My concern is how do you intend on accessing the the properties once the map is loaded?  There is the TiledMap.tile_properties dictionary, but the GID (the key) value will not be stable (it is not stable, per the TMX map spec).  You could hardcode those values, but they may change if your tilesets change.

If you just want a place to store key/value pairs, you could consider using custom properties on the Map object itself.

I've pushed my changes to the repo.  I'm going to wait a couple days do do some more testing or refactoring before pushing to pip.

**Comment by groug** [comment]
@bitcraft thanks, you were quick! I'll try to test it this week-end.

I cannot store anything in the Map, since what I want is to find unused tiles with the right properties.

Long story:
What I want is for the graphist to create maps, with one layer being what we want to display, and another one containing special tiles, like: what tiles will be considered as empty (to put some external stuff inside it), what tiles will be considered as "player's starting point", and more importantly what rows and columns will be considered as "expandable" (or not).
Then, the size of the map will be randomly set and could be greater or smaller than the loaded map size: knowing which rows and columns can be duplicated/removed to fit the final size, I will remove/duplicate rows/columns of tiles.
The trick, here, is that some of the tiles I want to duplicate can be replaced by other tiles from the same flag, the flag being a property of a tile in the tileset.

I was intending on accessing the properties with pytmx.TiledMap.get_tile_properties_by_gid, looping through all the tiles in the tileset, like the test script I gave you:

```python
tiled_map = pytmx.TiledMap(filename, load_all=True)
tileset = tiled_map.tilesets[0]
for gid in range(tileset.firstgid, tileset.firstgid + int(tileset.tilecount)):
    properties = tiled_map.get_tile_properties_by_gid(gid)
    if properties is not None:
        print(gid, properties)
```
What may be worth mentionning is that at the end I only use the rect info (and use this info to display the tile myself) with `get_tile_image_by_gid`

**Comment by groug** [comment]
Ok, I've installed the updated version of pytmx, I now get every tiles, and I seem to get all the tilesets' info I wanted (properties and rect). I used it in my game code, and everything seems fine, I'm able to replace some tiles of the map by other tiles from the tilesets with the same property "flag"!

By the way, you pushed some print!

**Comment by bitcraft** [comment]
Thanks for the detailed information.  When I started with Tiled, I also used special tiles for things like start position, enemy locations, etc.  It is easier to do that than using objects, in some cases.

Tiled tilesets are easily scriptable, if you are interested in auto generating them.  I did that a long time ago for a simple RPG type game....never finished.  The script below will create a TSX and and image, with properties for things like doors, enemies, items, etc.

https://github.com/bitcraft/mh/blob/master/utilities/mk_tileset.py

**Comment by groug** [comment]
Thanks for link :)
Your fix is good for me, I'm closing, waiting for the pip package to be updated!

**Comment by bitcraft** [comment]
Updated

**Comment by groug** [comment]
Tested with pip install, works as expected :)
Thanks again for the quick fix!
