### ISSUE TITLE
getting tile custom properties or tile "Type" (new in tiled 1.0)

### ISSUE THREAD

**Issue by RichardEllicott** [bitcraft/pytmx#89]
I can't seem to get the custom properties or the type i set, correct me if i'm wrong but i can use:

for obj in layer:  # iterate for tile IDs
(gives a tuple of x,y,ID ... no other data, this must be from the TMX file)

AND

for x, y, image in layer.tiles():  # iterate for image paths
(gives a tuple back like  ('images/block.png', None, None)), two Nones??

For the life of mean i can't get anything else out of TMX Files. The documentation says I should be able to get the "properties" but i never get anything other than tuples back.

The "Type" property apparently is new, it seems to be inline with the ID inside the XML file..... i'd be happy to just set custom properties

**Comment by DarkShroom** [comment]
UPDATE: (lol 5 minutes later as usual)

i think i have found the customer properties (thank god, i can use this thing then)... as the snippet: tiled_map.get_tile_properties(0,0,0) worked :)

sorry to to hassle you, i should likely mention i think the "Type" property is not yet supported, it nests in a different place, and it might conflict with your custom properties as the output i last got was:

{'width': '16', 'height': '16', 'source': 'images/block.png', 'key': 'block_key', 'frames': [], 'trans': None}

"key" being my custom property, and therefore it's in a place where if i choose the word "type" perhaps it'd bugger up (in a later version)

**Comment by bitcraft** [comment]
Thanks for bringing this to my attention.  For convenience (really, just my preference), the tiled object properties and the custom properties are bundled together in one dictionary.  I've found that some people like it, others don't.  You're right, it may cause conflicts; see below.

https://github.com/bitcraft/PyTMX/#reserved-names

**Comment by bitcraft** [comment]
added
