### ISSUE TITLE
No video mode has been set

### ISSUE THREAD

**Issue by yarden22** [bitcraft/PyTMX#90]
hello, this is the part of my code who is relevance to pytmx
1.    def __init__(self, filename):
2.        tm = load_pygame(filename, pixelalpha=True)
3.        self.width = tm.width * tm.tilewidth
4.        self.height = tm.height * tm.tileheight
5.        self.tmxdata = tm 

and more.... but  my problem starts in line 2. , i try to run and the error is this:
  File "C:\Users\Yarden\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytmx\util_pygame.py", line 50, in smart_convert
    tile = original.convert()
pygame.error: No video mode has been set

how can i fix it?
thank you for helping

**Comment by menacingChicken** [comment]
I don't think this is a bug (developers can correct me here). Pygame requires you to init the library before use. Further, before using any of the Surface objects, a display must be present. So you have to do that as well. Something like this:

`import pytmx
from pytmx.util_pygame import load_pygame
import pygame

pygame.init()
display = pygame.display.set_mode((400, 400), pygame.HWSURFACE | pygame.DOUBLEBUF)

m = load_pygame('assets/desert.tmx')`

**Comment by bitcraft** [comment]
Thank you, @menacingChicken; you are correct.  If you load tiles with pygame and pytmx (optional!), you must have a display set first.  This is a pygame limitation.  @yarden22 please let me know if your issue is resolved.
