### ISSUE TITLE
Parse custom property types

### ISSUE THREAD

**Issue by gusg21** [bitcraft/PyTMX#91]
From my use of PyTMX I have repeatedly run into the same problem of having to convert custom properties to ints even though the type of a custom property is defined in the .tmx file. Is this a planned feature, or should I fork the repository and try to do it myself?

**Comment by bitcraft** [comment]
Pytmx has lagged behind Tiled version lately.  I don't have support for property types.  If you have a fix for it, I'm willing to merge it.  Right now, I can't see myself working on it at least for a couple weeks.  Sorry about that.

**Comment by macskay** [comment]
Property types are now parsed to Python builtin-types.
 - int -> int
 - float -> float
 - bool -> bool
 - string, file, color -> string

**Comment by macskay** [comment]
@bitcraft: I think this can be closed then.
