### ISSUE TITLE
Tileset (.tsx file) Collision Parsing?

### ISSUE THREAD

**Issue by jsprada** [bitcraft/pytmx#93]
First of all, thank you for PyTMX, it's pretty great!!

Tiled has a neat feature that will allow us to define collision polygons on the tileset.   These aren't transferred to the .tmx file, it sounds like they will always live in the .tsx.  As of now, if they're defined in Tiled, they're ignored by PyTMX.   It would be fantastic if PyTMX would include these. 

Has there been any thought to adding a feature to PyTMX to parse the .tsx file for these collisions (and perhaps create a list of rectangles, or at least return a (x, y, h, w) tuple that the user can use to create them?

Thank you

**Comment by menacingChicken** [comment]
This would be a fantastic feature to add in! I defined my collision maps on to the tiles themselves. Would be nice to get those added to the tilemap. The hard part I see here is mapping the x,y coordinates of the tileset objectgroups to their respective positions within the tilemap.

**Comment by bitcraft** [comment]
I agree this would be a great feature to have.  I can look into it.

**Comment by jsprada** [comment]
This would be most excellent!   There's one "gotcha," noted from the author of Tiled, that the tilesets are stored by x/y coordinates from the bottom left of each tile, if I'm not mistaken.

**Comment by bitcraft** [comment]
Any ideas of a convenient way to access the collision information?  Maybe add a collision polygon/polyline to the tile properties dictionary?

**Comment by jsprada** [comment]
@bitcraft
 

I just took a look at my .tsx file that has tile collisions defined.   Here's an example that has two collisions set up on one tile (it's a corner piece):
```

</tile>
 <tile id="23" terrain="0,1,1,1">
  <objectgroup draworder="index" name="walls">
   <object id="1" name="wall" type="wall" x="0" y="8" width="16" height="8"/>
   <object id="2" name="wall" type="wall" x="8" y="0" width="8" height="8"/>
  </objectgroup>
 </tile>
```

Maybe if the tile properties dictionary could contain a collisions dictionary. 

Keys for the dictionary could by an ID, and hold a tuple with (name, type, x, y, w, h)

Unless I'm missing something, that seems like it should be simple enough to implement, and generic enough that anyone should be able to access the values to do with them as they please when iterating through the tile objects. 

I do realize that you have built a pretty cool (I think you called it a kludge, when I read the code.  I disagree, and think it was rather brilliant!) option to merge collision polygons on a best effort basis.   A future version might attempt to do that for these tile collisions, but that would be a fair bit more difficult than searching for and joining boundaries that are all equal size of the tiles, like you're doing already.

Thank you for your consideration!

**Comment by bitcraft** [comment]
I like that idea of merging the tileset collisions into some large structure.  I'm not sure where I would start with that, since depending on your collision handling, you would want different formats (box2d, chipmunk, pygame, etc require different formats for the shapes).

**Comment by jsprada** [comment]
I can only speak for pygame, but presumably, is it safe to assume that any of them could make use of a list of  tuples containing (x, y, w, h) dimensions for the merged areas?  This would only support merging items into large rectangles, rather than complex polygons, but I assume it would cover most use cases.  
   

I'm not sure how to create a collision boundary for box2d, or chipmunk, but I would have to assume that they could use the same basic dimensions/coords as pygame.   If they don't, I have to assume that a user could easily convert them to the proper format.  I think that would be most excellent for users of each of the mentioned libraries to create the collisions in their own way.

**Comment by bitcraft** [comment]
added in mason branch.  will be available soon

**Comment by bitcraft** [comment]
feature added in latest build.  documentation is here: https://github.com/bitcraft/pytmx/#get-tile-colliders
