### ISSUE TITLE
Adding Object Layer causes AttributeError

### ISSUE THREAD

**Issue by jainokaine** [bitcraft/PyTMX#96]
When looping through layers through a map without an object layer, everything works fine. However when I add an object layer to the map, it raises an AttributeError; even if that layer is empty.

> File "E:\Game Projects\Deathmask\engine\map.py", line 19, in __init__
>     for x, y, i in layer.tiles():
>   File "C:\Users\myoga\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytmx\pytmx.py", line 277, in __getattr__
>     raise AttributeError
> AttributeError

My code is:

```
mapData = pytmx.TiledMap('test.tmx')
        for layer in self.map.layers:
            for x, y, i in layer.tiles():
                # put stuff in object array
```

**Comment by bitcraft** [comment]
The layer attribute will return all layers. Try using “visible_tile_layers”
instead.

**Comment by macskay** [comment]
I handle this issue like this normally:


    self.map = self.load_map() 
    def load_map(self):
        return pytmx.util_pygame.load_pygame(resources.get_map_asset('mymap.tmx'))

    def get_layers(self):
        for layer in self.map:
            if isinstance(layer, pytmx.TiledTileLayer):
                yield layer


If I want to iterate over the Object Groups then I do the following

    def can_walk_to_pos(self, sprite, x, y):
        new_pos = self.get_scaled_position((sprite.rect.x+x, sprite.rect.y+y))
        for obj in self.get_object_group("Walls"):
            obj = self.convert_object_to_rect(obj)
            size = sprite.rect.width // self.scaling[0], sprite.rect.height // self.scaling[1]
            rect = pygame.Rect(new_pos, size)
            if obj.colliderect(rect):
                return False
        return True

    def get_object_group(self, name):
        for og in self.map.objectgroups:
            if og.name == name:
                return og

This way I can either iterate over layers, which I want to render and layers which hold objects.

**Comment by bitcraft** [comment]
@macskay There is a built in method to get a layer by name:  https://github.com/bitcraft/PyTMX/blob/master/pytmx/pytmx.py#L666-L677
