### ISSUE TITLE
load_all_tiles

### ISSUE THREAD

**Issue by mgoral** [bitcraft/pytmx#97]
Hi,

documentation and comments mention that `TileMap` accepts parameter named `load_all_tiles`, however code checks for `load_all` passed as keyword argument:

```
self.load_all_tiles = kwargs.get('load_all', True)
```

i.e. this will silently disregard passed parameter:

```
tm = TileMap(file_, load_all_tiles=False)
```

I think this should be changed this way or the other.

**Comment by bitcraft** [comment]
That’s a good point. I’ll look into a good solution that won’t break
everybody’s code. :)

**Comment by bitcraft** [comment]
should be fixed now
